version: "3.9"

services:
  node_pure_server:
    build:
      context: ./nodejs_server/pure_server
    container_name: node_pure_server
    ports:
      - "8081:8081"
    restart: unless-stopped

  node_socketio_server:
    build:
      context: ./nodejs_server/socketIo_server
    container_name: node_socketio_server
    ports:
      - "8082:8082"
    restart: unless-stopped

  fastapi_server:
    build:
      context: ./fastapi_server
    container_name: fastapi_server
    ports:
      - "8083:8083"
    restart: unless-stopped

  spring_server:
    build:
      context: ./spring_server
    container_name: spring_server
    ports:
      - "8080:8080"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node_pure_server
      - node_socketio_server
      - fastapi_server
      - spring_server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus