version: "3.9"

services:
  # ──────── WebSocket 서버 ────────
  node_pure_server:
    build:
      context: ./nodejs_server/pure_server
    container_name: node_pure_server
    ports:
      - "8081:8081"
    restart: unless-stopped
    profiles:
      - servers

  node_socketio_server:
    build:
      context: ./nodejs_server/socketIo_server
    container_name: node_socketio_server
    ports:
      - "8082:8082"
    restart: unless-stopped
    profiles:
      - servers

  fastapi_server:
    build:
      context: ./fastapi_server
    container_name: fastapi_server
    ports:
      - "8083:8083"
    restart: unless-stopped
    profiles:
      - servers

  spring_server:
    build:
      context: ./spring_server
    container_name: spring_server
    ports:
      - "8080:8080"
    restart: unless-stopped
    profiles:
      - servers

  # ──────── 인프라: VictoriaMetrics + Grafana ────────
  vmetrics:
    image: victoriametrics/victoria-metrics:v1.98.0
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    command:
      - '-promscrape.config=/etc/prometheus.yml'
      - '-retentionPeriod=30d'
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus.yml
    restart: unless-stopped
    profiles:
      - infra

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - vmetrics
    profiles:
      - infra

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    profiles:
      - infra

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles:
      - infra

  # ──────── k6 클라이언트 ────────
  k6_fastapi:
    build:
      context: ./client_test/k6_client
    container_name: k6_fastapi
    environment:
      - TARGET_URL=ws://fastapi_server:8083/ws
    profiles:
      - clients

  k6_node_pure:
    build:
      context: ./client_test/k6_client
    container_name: k6_node_pure
    environment:
      - TARGET_URL=ws://node_pure_server:8081
    profiles:
      - clients

  k6_node_socketio:
    build:
      context: ./client_test/k6_client
    container_name: k6_node_socketio
    environment:
      - TARGET_URL=ws://node_socketio_server:8082/socket.io/?EIO=4&transport=websocket
    profiles:
      - clients

  k6_spring_pure:
    build:
      context: ./client_test/k6_client
    container_name: k6_spring_pure
    environment:
      - TARGET_URL=ws://spring_server:8080/ws-native
    profiles:
      - clients

  k6_spring_stomp:
    build:
      context: ./client_test/k6_client
    container_name: k6_spring_stomp
    environment:
      - TARGET_URL=ws://spring_server:8080/ws-stomp/websocket
    profiles:
      - clients
