version: "3.9"

services:
  pure_server:
    build:
      context: ./nodejs_server/pure_server
    container_name: node_pure_server
    ports:
      - "8081:8081"
    restart: unless-stopped

  socketio_server:
    build:
      context: ./nodejs_server/socketIo_server
    container_name: node_socketio_server
    ports:
      - "8082:8082"
    restart: unless-stopped

  fastapi_server:
    build:
      context: ./fastapi_server
    container_name: fastapi_server
    ports:
      - "8083:8083"
    restart: unless-stopped

  spring_server:
    build:
      context: ./spring_server
    container_name: spring_server
    ports:
      - "8080:8080"
    restart: unless-stopped
